import { AUDIO_STATE } from "./types";

export const initAudio: AUDIO = {
  artistId: 0,
  artistName: "",
  artistViewUrl: "",
  artworkUrl30: "",
  artworkUrl60: "",
  artworkUrl100: "",
  collectionCensoredName: "",
  collectionExplicitness: "",
  collectionId: 0,
  collectionName: "",
  collectionPrice: 0,
  collectionViewUrl: "",
  country: "",
  currency: "",
  discCount: 0,
  discNumber: 0,
  isStreamable: false,
  kind: "",
  previewUrl: "",
  primaryGenreName: "",
  releaseDate: "",
  trackCensoredName: "",
  trackCount: 0,
  trackExplicitness: "",
  trackId: 0,
  trackName: "",
  trackNumber: 0,
  trackPrice: 0,
  trackTimeMillis: 0,
  trackViewUrl: "",
  wrapperType: "",
  copyright: "",
  description: "",
};

export const initialState: AUDIO_STATE = {
  //   audioBooks: [],
  //   songs: [],
  audios: [],
  playingSong: initAudio,
  isLoading: false,
  isOffsetLoading: false,
  isPlaying: false,
  error: "",
  searchParam: "eminem",
  offsetParam: 0,
};
